#!/usr/bin/env python3
"""Conclude the current season and create an end-of-season tournament.

Reads the combined leaderboard, selects the top N players by Elo rating,
locks in their preset/personality/effort for all tournament games, and
transitions the season to tournament phase.

Usage:
    python scripts/conclude_season.py <tournament_size>
    # tournament_size is typically 8 or 16
"""

import json
import random
import sys
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_SEASON_FILE = _ROOT / "data" / "season.json"
_TOURNAMENTS_DIR = _ROOT / "data" / "tournaments"
_BENCHMARK_RESULTS = _ROOT / "website" / "src" / "data" / "benchmark-results.json"
_PRESETS_JSON = _ROOT / "puppeteer" / "presets.json"
_PERSONALITIES_JSON = _ROOT / "puppeteer" / "personalities.json"


def _build_key_to_preset(presets_data: dict) -> dict[str, str]:
    """Build player_key -> preset_name mapping from presets.json."""
    mapping: dict[str, str] = {}
    for name, pdata in presets_data.get("presets", {}).items():
        model_id = pdata.get("model", "")
        effort = pdata.get("reasoning_effort")
        key = f"{model_id}::{effort}" if effort else model_id
        mapping[key] = name
    return mapping


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: conclude_season.py <tournament_size>", file=sys.stderr)
        print("  e.g.: conclude_season.py 8", file=sys.stderr)
        return 2

    size = int(sys.argv[1])
    assert size in (8, 16), f"Tournament size must be 8 or 16, got {size}"

    # Load current season state
    assert _SEASON_FILE.exists(), f"Season file not found: {_SEASON_FILE}"
    season_data = json.loads(_SEASON_FILE.read_text())
    assert season_data["phase"] == "free-play", (
        f"Season {season_data['current_season']} is already in phase "
        f"'{season_data['phase']}', cannot conclude"
    )
    season_num = season_data["current_season"]

    # Load combined leaderboard (generated by `make leaderboard`)
    assert _BENCHMARK_RESULTS.exists(), (
        f"Leaderboard data not found at {_BENCHMARK_RESULTS}. "
        f"Run 'make leaderboard' first."
    )
    benchmark = json.loads(_BENCHMARK_RESULTS.read_text())
    combined_models = benchmark.get("models", [])

    assert len(combined_models) >= size, (
        f"Only {len(combined_models)} models in combined leaderboard, "
        f"need {size} for tournament"
    )

    # Top N by combined Elo (already sorted by rating desc in leaderboard)
    top_models = combined_models[:size]

    # Load presets to map model keys back to preset names
    presets_data = json.loads(_PRESETS_JSON.read_text())
    key_to_preset = _build_key_to_preset(presets_data)

    # Load personalities and assign randomly (unique per entrant)
    personalities = json.loads(_PERSONALITIES_JSON.read_text())
    personality_keys = list(personalities.keys())
    random.shuffle(personality_keys)
    assert len(personality_keys) >= size, (
        f"Only {len(personality_keys)} personalities available, need {size}"
    )

    # Build entrants list
    entrants = []
    for i, model in enumerate(top_models):
        model_id = model["modelId"]
        effort = model.get("reasoningEffort")
        key = f"{model_id}::{effort}" if effort else model_id
        preset_name = key_to_preset.get(key)
        assert preset_name is not None, (
            f"No preset found for model key {key!r}. Is this model in presets.json?"
        )

        personality = personality_keys[i]

        entrant: dict = {
            "seed": i + 1,
            "preset": preset_name,
            "model": model_id,
            "display_name": model["modelName"],
            "personality": personality,
            "combined_elo": model["rating"],
            "games_played": model["gamesPlayed"],
        }
        if effort:
            entrant["reasoning_effort"] = effort
        entrants.append(entrant)

    # Create tournament file
    _TOURNAMENTS_DIR.mkdir(parents=True, exist_ok=True)
    tournament_file = _TOURNAMENTS_DIR / f"season-{season_num}.json"
    assert not tournament_file.exists(), (
        f"Tournament file already exists: {tournament_file}"
    )

    tournament = {
        "season": season_num,
        "size": size,
        "format": "single-elimination",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "entrants": entrants,
        "rounds": [],
    }

    tournament_file.write_text(json.dumps(tournament, indent=2) + "\n")
    print(f"Tournament created -> {tournament_file}")

    # Update season state to tournament phase
    season_data["phase"] = "tournament"
    season_data["tournament"] = f"data/tournaments/season-{season_num}.json"
    _SEASON_FILE.write_text(json.dumps(season_data, indent=2) + "\n")
    print(f"Season {season_num} moved to tournament phase -> {_SEASON_FILE}")

    # Print the bracket seeding
    print(f"\nSeason {season_num} Tournament -- Top {size} by Combined Elo:")
    print("=" * 70)
    for e in entrants:
        effort_str = f" ({e['reasoning_effort']})" if "reasoning_effort" in e else ""
        print(
            f"  #{e['seed']:2d}  {e['display_name']}{effort_str}  "
            f"[Elo {e['combined_elo']}]  "
            f"personality: {e['personality']}"
        )
    print()
    print("Free-play games are now blocked. Use tournament targets to proceed.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
